// Code generated by tygo. DO NOT EDIT.

//////////
// source: spotify.go

export interface SpotifyUser {
  id: string;
  display_name: string;
  images: SpotifyImageArray;
}
export interface SpotifyArtist {
  id: string;
  name: string;
  images: SpotifyImageArray;
}
export interface SpotifyAlbum {
  id: string;
  name: string;
  images: SpotifyImageArray;
}
export interface SpotifyTrack {
  id: string;
  name: string;
  artists: SpotifyArtist[];
  album: SpotifyAlbum;
}
export interface SpotifyPlaylist {
  id: string;
  snapshot_id: string;
  name: string;
  images: SpotifyImageArray;
}
export interface SpotifyPlaylistTrack {
  playlist_id: string;
  track_id: string;
  added_at: string /* RFC3339 */;
  added_by: string;
}

//////////
// source: spotify_image.go

export interface SpotifyImage {
  url: string;
  height: number /* int */;
  width: number /* int */;
}
export type SpotifyImageArray = SpotifyImage[];
